attempt 1 css-brochure-form
Yi-Jacob/c0122-code-solutions pull request #15
Opened 2022-01-27 17:05 UTC by jacobyi11

![Screen Shot 2022-01-27 at 8 54 24 AM](https://user-images.githubusercontent.com/96788421/151407798-684a91d1-771e-4fe7-b6b4-898ed0063c3d.png)

2022-01-27 18:13 UTC, codingcodymiller requested changes
Hey Jacob, your inputs are too wide and are not styled correctly to match the example, please revise and submit a new screenshot with your revision.

2022-01-27 23:16 UTC, jacobyi11 commented
![Screen Shot 2022-01-27 at 3 14 16 PM](https://user-images.githubusercontent.com/96788421/151459105-82418b7c-7da7-4d6e-a496-5ddeadfccf83.png)

2022-01-28 19:07 UTC, codingcodymiller requested changes
Hey Jacob! The borders on your input and select elements are different from the example, and your SUBMIT button is indented a bit from the right side of the select, where it should be resting against the right edge of the select element, please revise and submit a new screenshot with your revision.

2022-01-28 20:51 UTC, jacobyi11 commented
![Screen Shot 2022-01-28 at 12 47 51 PM](https://user-images.githubusercontent.com/96788421/151619628-b928d0c3-e413-4614-a9be-caa3e5b1f0e4.png)

2022-01-28 23:11 UTC, codingcodymiller requested changes

2022-01-28 23:11 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  src: url("BrandonGrotesque-Regular.woff2") format("woff2");
These are only necessary for the @font-face rule, not using the font. You can just state the name of the fonts in the `fonts.css` file in the `font-family` property values to use it.

2022-01-28 23:11 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 50%;
😱 😱 😱 😱 

That's a **_lot_** of margin. Why is this necessary? There is likely a better way to accomplish this.

2022-01-28 23:11 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-top: 75%;
😱 😱 😱 😱 

That's a **_lot_** of margin. Why is this necessary? There is likely a better way to accomplish this.

2022-01-28 23:11 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  text-align: 80%;
`text-align` doesn't accept percentage values, this is doing nothing.

2022-01-28 23:11 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  right: 555px;
😱 😱 😱 😱 😱 😱 

You can do this in a better way.

2022-01-29 01:00 UTC, jacobyi11 commented
![Screen Shot 2022-01-28 at 4 59 04 PM](https://user-images.githubusercontent.com/96788421/151640476-584b94fe-c3d2-42d0-a0f7-f4960030efb1.png)
i cleaned up some of the code

2022-01-31 17:27 UTC, codingcodymiller requested changes

2022-01-31 17:27 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  left: 245px;
This is just the same problem from a different side. You are pushing the element where you want it to be, which will break colossally when mobile responsiveness comes into play. You should use `text-align: right` to move the button to the right-hand side of the `div`, that will get you the same behavior in a way that works across all screen sizes.

2022-01-31 17:44 UTC, jacobyi11 commented
![Screen Shot 2022-01-31 at 9 43 00 AM](https://user-images.githubusercontent.com/96788421/151845301-f4a54007-98f8-4efc-8025-6115c53ee08b.png)

sorry about that.

2022-02-01 18:19 UTC, codingcodymiller requested changes

2022-02-01 18:19 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  padding-right: 3rem;
Why is the padding necessary here? What happens if you leave it out?

2022-02-01 19:04 UTC, jacobyi11 commented
![Screen Shot 2022-02-01 at 11 01 51 AM](https://user-images.githubusercontent.com/96788421/152033693-d4e6707b-0964-4c92-9a23-8aac60f279d0.png)
the width of the buttons were not 100% so thats why i had padding but i changed it to 100% so now the padding was not needed

2022-02-01 23:15 UTC, codingcodymiller approved these changes
Nice work!!

2022-02-01 23:22 UTC, merged