completed css-flexbox
Yi-Jacob/c0122-code-solutions pull request #16
Opened 2022-01-27 18:34 UTC by jacobyi11

![Screen Shot 2022-01-27 at 10 30 35 AM](https://user-images.githubusercontent.com/96788421/151421914-95ca16f0-11e9-44e1-b64d-ff551f8cd46a.png)
![Screen Shot 2022-01-27 at 10 28 51 AM](https://user-images.githubusercontent.com/96788421/151421924-c0c70946-0fc2-49c8-a53e-233e5ba8b9ca.png)
![Screen Shot 2022-01-27 at 10 26 47 AM](https://user-images.githubusercontent.com/96788421/151421933-a1b8c11b-51df-4442-9c5b-32e42b4889f5.png)
![Screen Shot 2022-01-27 at 10 24 59 AM](https://user-images.githubusercontent.com/96788421/151421935-9013bec2-3be4-4910-8f7d-3ead3bfaecb9.png)

2022-01-27 18:43 UTC, codingcodymiller requested changes
_**WOAH**_, you have **_58_** files included in this pull request. Did you use the command `git add .` or do something unusual when committing?

2022-01-28 01:06 UTC, codingcodymiller requested changes

2022-01-28 01:06 UTC, codingcodymiller commented on css-flexbox/flex-wrap.html
> +      flex-wrap: wrap;
The `flex-wrap` property should be applied to the same element that `display: flex` is applied to

2022-01-28 01:10 UTC, jacobyi11 commented
![Screen Shot 2022-01-27 at 5 09 26 PM](https://user-images.githubusercontent.com/96788421/151469393-db9c5a19-b1ee-4c36-b1e1-a9638f5df42f.png)

2022-01-28 01:45 UTC, codingcodymiller approved these changes

2022-01-28 17:56 UTC, merged