Css three column layout
Yi-Jacob/c0122-code-solutions pull request #18
Opened 2022-01-28 04:00 UTC by jacobyi11

![Screen Shot 2022-01-27 at 7 58 04 PM](https://user-images.githubusercontent.com/96788421/151485085-5acbfc97-8264-4aa7-a944-c10fa96edc41.png)

2022-01-28 21:23 UTC, jacobyi11 commented
![Screen Shot 2022-01-28 at 1 17 52 PM](https://user-images.githubusercontent.com/96788421/151623381-f85aa1d9-5181-4482-9303-289dacfd80e3.png)

2022-01-28 23:25 UTC, codingcodymiller requested changes

2022-01-28 23:25 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
Column classes should only include `flex-basis` or `width`, anything else should be a separate class. You need to keep your layout classes untainted and reusable.

2022-01-28 23:25 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
Column classes should only include `flex-basis` or `width`, anything else should be a separate class. You need to keep your layout classes untainted and reusable.

2022-01-29 01:03 UTC, jacobyi11 commented
![Screen Shot 2022-01-28 at 5 02 47 PM](https://user-images.githubusercontent.com/96788421/151640618-5bb7687b-5ead-4154-b636-23162c42f498.png)

2022-01-31 17:36 UTC, codingcodymiller requested changes
Hey Jacob, the font size and weight for the subheader and text in each column do not match the example, please revise and submit a new screenshot with your revision. It may be helpful to use the actual text so that you can gauge the quality of your output better.

2022-01-31 23:05 UTC, jacobyi11 commented
![Screen Shot 2022-01-31 at 3 04 58 PM](https://user-images.githubusercontent.com/96788421/151887680-8ca98d77-6ef7-476c-b109-65e6417d11a5.png)

2022-02-01 18:24 UTC, codingcodymiller requested changes

2022-02-01 18:24 UTC, codingcodymiller commented on css-three-column-layout/index.html
> +      <div class="column-main">
`column-main`? What's its size? This isn't how `column` classes are meant to be named.

2022-02-01 18:24 UTC, codingcodymiller commented on css-three-column-layout/index.html
> +      <div class="column">
`column` what?

2022-02-01 18:58 UTC, codingcodymiller approved these changes

2022-02-01 18:58 UTC, jacobyi11 commented
![Screen Shot 2022-02-01 at 10 56 59 AM](https://user-images.githubusercontent.com/96788421/152032992-2f2c0921-8581-4466-900f-cd1d073cb823.png)
thank you, i changed the names of the coulmns

2022-02-01 18:59 UTC, merged