Css two column layout
Yi-Jacob/c0122-code-solutions pull request #20
Opened 2022-01-29 00:49 UTC by jacobyi11

![Screen Shot 2022-01-28 at 4 47 46 PM](https://user-images.githubusercontent.com/96788421/151639984-eb57356a-a7b6-40a9-85a4-21177a3defd0.png)

2022-01-31 18:18 UTC, codingcodymiller requested changes
Hey Jacob, all your `column` classes are named after what they are being used on, not their measurement, which is not the way that `column` classes are meant to be structured. Please review `css-layout-classes` and then revise your layout classes in this challenge to match their intended purpose.

2022-01-31 18:50 UTC, jacobyi11 commented
![Screen Shot 2022-01-31 at 10 49 15 AM](https://user-images.githubusercontent.com/96788421/151854413-9ca7f21a-f372-4f6e-8f7c-8172d52850d2.png)

2022-01-31 22:50 UTC, codingcodymiller requested changes

2022-01-31 22:50 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 425px;
Please redo this without abusing `margin`

2022-01-31 22:50 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-left: 425px;
I suggest using `text-align` to center the button.

2022-01-31 22:50 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column {
`column-half`?

2022-01-31 22:50 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-right: 10%;
`column` classes should only have `flex-basis` or `width` and nothing else. You should make an additional class you can add to the element in addition to the column class.

2022-02-01 00:54 UTC, jacobyi11 commented
![Screen Shot 2022-01-31 at 4 52 36 PM](https://user-images.githubusercontent.com/96788421/151897088-d738e3a5-1d3b-4d33-aa3e-a89985a5638a.png)

2022-02-01 20:51 UTC, jacobyi11 commented
![Screen Shot 2022-02-01 at 12 50 36 PM](https://user-images.githubusercontent.com/96788421/152049258-1c1f72e5-7b7a-4174-8255-0df5c75ad6b2.png)

2022-02-01 23:21 UTC, codingcodymiller approved these changes
Nice work!

2022-02-10 00:13 UTC, merged