Css four column layout
Yi-Jacob/c0122-code-solutions pull request #30
Opened 2022-02-02 19:25 UTC by jacobyi11

![Screen Shot 2022-02-02 at 11 23 51 AM](https://user-images.githubusercontent.com/96788421/152222527-60d3b206-afbe-429a-bd5b-42938c13a73d.png)

2022-02-04 19:41 UTC, codingcodymiller requested changes
Hey Jacob! The font weight of the headers in your output does not match the example, please revise and submit a new screenshot with your revision.

2022-02-05 23:26 UTC, jacobyi11 commented
![Screen Shot 2022-02-05 at 3 25 53 PM](https://user-images.githubusercontent.com/96788421/152662329-e701f040-c43a-4274-bd42-39879d454d62.png)

2022-02-05 23:26 UTC, jacobyi11 commented
![Screen Shot 2022-02-05 at 3 26 46 PM](https://user-images.githubusercontent.com/96788421/152662349-c5d57e02-e477-4f80-b757-9d67d45be24b.png)

2022-02-07 18:07 UTC, codingcodymiller approved these changes

2022-02-07 19:07 UTC, merged