String manipulation 3
Yi-Jacob/c0122-code-solutions pull request #70
Opened 2022-03-01 04:38 UTC by jacobyi11

![Screen Shot 2022-02-28 at 8 25 58 PM](https://user-images.githubusercontent.com/96788421/156105777-6d24836d-99dd-432d-b76f-2c6b90e370cb.png)

2022-03-07 02:59 UTC, jacobyi11 commented
![Screen Shot 2022-03-06 at 6 54 18 PM](https://user-images.githubusercontent.com/96788421/156960346-b1e08092-75b1-43d6-a134-f9db747c35a5.png)

2022-03-11 18:30 UTC, codingcodymiller requested changes

2022-03-11 18:30 UTC, codingcodymiller commented on string-manipulation-3/src/title-case.js
> +  if (words[0].charAt(0) === 'J') {
Any title with a first word starting with `J` will now have that word replaced with "JavaScript"

2022-05-04 01:39 UTC, Yi-Jacob commented
![Screen Shot 2022-05-03 at 6 39 41 PM](https://user-images.githubusercontent.com/96788421/166612686-ae55b633-dab6-4a33-a415-11ee9d558497.png)

2022-05-04 16:09 UTC, thebearingedge approved these changes

2022-05-04 17:23 UTC, merged